name: GitHub Action for Slack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Action for Slack
        env:
         #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          #SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
          SLACK_CHANNEL: chatops-github # Optional. (defaults to webhook)
          #SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@2.0.1
        with:
          # The message to display in the Slack notification.
          args: "Commit ID => ${{ github.sha }}"
